### ISSUE TITLE
if statement in ViewHelper incorrect

### ISSUE THREAD

**Issue by kleffsche** [dansol/webpack-encore-view-helper#1]
Hi, 

thank you very much for providing this usefull helper. 

I've found out, that his statement below causes the helper to fail:

```
if (  $webPackEntryPoint ==='auto' || $webPackEntryPoint==='auto-child'){
            // find template name from child view ( assumed captureTo is "content")
            $childModel=$layout->getChildrenByCaptureTo('content',false);
            if (!is_array($childModel) ){
                throw new Exception\InvalidArgumentException('cannot detect child view model template name');
            }

            $templateFullName=$childModel[0]->getTemplate();
            $wpEntryPoint= $this->getWebpackentryFromTemplate($templateFullName);
            $this->loadAssets($wpEntryPoint, $type);

  }
```

When using `$this->webpack_encore_assets('auto');` in my default layout the application will not work. Changing the statement to `if ( $webPackEntryPoint==='auto-child'){` it works. 

Have I perhaps overlooked something, or is this a mistake?

**Comment by dansol** [comment]
Hi,
Could you please provide more details about your layout structure and setup? 
You can also see a working example in mezzio-skeleton-webpack-encore-sample repo.

**Comment by kleffsche** [comment]
Thank you. It works now, after some testing.  

`$this->webpackEncoreAssets('app');`
